int ** create_2D_dyn(int line, int column);
void free_2D(int line,int ** c);
void display_board(int line , int column,int ** p,int score);
int ** fill_location_tab(int line, int column,int ** p, int i);
void display_blocks(int line,int column, int * shape,int x);
void display_line_pretty(int Cell,int Max,int position);
int ** select_blocks(int line, int column,int i);
int check_validity(int x, int y,int n, int m ,int line,int column,int ** board,int ** block);
void place_block(int x, int y , int n, int m , int ** board , int ** block);
int state_line ( int y, int Size, int ** board);
void eliminate_line (int line, int Size,int ** board );
void eliminate_column(int column, int Size,int ** board );
void state_board(int y_coord,int x_coord,int n,int m,int column,int line,int ** board,int * score);
void shift_lines(int y_coord,int column,int ** board);
void title();
void initialisation();
void Score(int * score);
int ** create_block_B0(int line, int column);
int ** create_block_B1(int line, int column);
int ** create_block_B2(int line, int column);

int ** create_block_A0(int line, int column);
int ** create_block_A1(int line, int column);
int ** create_block_A2(int line, int column);
int ** create_block_A3(int line, int column);
int ** create_block_A4(int line, int column);
int ** create_block_A5(int line, int column);
int ** create_block_A6(int line, int column);
int ** create_block_A7(int line, int column);
int ** create_block_A8(int line, int column);
int ** create_block_A9(int line, int column);
int ** create_block_A10(int line, int column);
int ** create_block_A11(int line, int column);
int ** create_block_A12(int line, int column);
int ** create_block_A13(int line, int column);
int ** create_block_A14(int line, int column);
int ** create_block_A15(int line, int column);
int ** create_block_A16(int line, int column);
int ** create_block_A17(int line, int column);
int ** create_block_A18(int line, int column);
int ** create_block_A19(int line, int column);

int ** create_block_C0(int line, int column);
int ** create_block_C1(int line, int column);
int ** create_block_C2(int line, int column);
int ** create_block_C3(int line, int column);
int ** create_block_C4(int line, int column);
int ** create_block_C5(int line, int column);
int ** create_block_C6(int line, int column);
int ** create_block_C7(int line, int column);
int ** create_block_C8(int line, int column);
int ** create_block_C9(int line, int column);
int ** create_block_C10(int line, int column);
int ** create_block_C11(int line, int column);

int ** create_block_D0(int line, int column);
int ** create_block_D1(int line, int column);
int ** create_block_D2(int line, int column);
int ** create_block_D3(int line, int column);
int ** create_block_D4(int line, int column);
int ** create_block_D5(int line, int column);
int ** create_block_D6(int line, int column);
int ** create_block_D7(int line, int column);
int ** create_block_D8(int line, int column);
int ** create_block_D9(int line, int column);
int ** create_block_D10(int line, int column);
int ** create_block_D11(int line, int column);
int ** create_block_D12(int line, int column);
int ** create_block_D13(int line, int column);

int ** create_block_T0(int line, int column);
int ** create_block_T1(int line, int column);
int ** create_block_T2(int line, int column);
int ** create_block_T3(int line, int column);
int ** create_block_T4(int line, int column);
int ** create_block_T5(int line, int column);
int ** create_block_T6(int line, int column);
int ** create_block_T7(int line, int column);
int ** create_block_T8(int line, int column);
int ** create_block_T9(int line, int column);
int ** create_block_T10(int line, int column);

